mixed-port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: '127.0.0.1:9090'
secret: "123456"
experimental:
  ignore-resolve-fail: true
  # interface-name: en0 # outbound interface name
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
     - '*.lan'
     - localhost.ptlogin2.qq.com
  nameserver:
     - 180.76.76.76
     - 119.29.29.29
  fallback:
  fallback-filter:
     geoip: true
     ipcidr:
       - 240.0.0.0/4
